api_platform:
    title: 'SISE-AGER API'
    description: 'Socle API backend pour la plateforme SISE-AGER dédiée au PNER 2040 / AGER.'
    version: '0.1.0'
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 30
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
