<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260606030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER financing module tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bailleur_fonds (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, type_bailleur VARCHAR(30) NOT NULL, pays VARCHAR(100) DEFAULT NULL, contact_principal VARCHAR(150) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BAILLEUR_FONDS_CODE ON bailleur_fonds (code)');

        $this->addSql('CREATE TABLE source_financement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bailleur_fonds_id INT DEFAULT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, type_source VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SOURCE_FINANCEMENT_BAILLEUR_FONDS_ID ON source_financement (bailleur_fonds_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SOURCE_FINANCEMENT_CODE ON source_financement (code)');
        $this->addSql('ALTER TABLE source_financement ADD CONSTRAINT FK_SOURCE_FINANCEMENT_BAILLEUR_FONDS FOREIGN KEY (bailleur_fonds_id) REFERENCES bailleur_fonds (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE convention_financement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bailleur_fonds_id INT NOT NULL, source_financement_id INT DEFAULT NULL, programme_pner_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, intitule VARCHAR(200) NOT NULL, montant_usd DOUBLE PRECISION NOT NULL, date_signature DATE DEFAULT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, statut VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CONVENTION_FINANCEMENT_BAILLEUR_FONDS_ID ON convention_financement (bailleur_fonds_id)');
        $this->addSql('CREATE INDEX IDX_CONVENTION_FINANCEMENT_SOURCE_FINANCEMENT_ID ON convention_financement (source_financement_id)');
        $this->addSql('CREATE INDEX IDX_CONVENTION_FINANCEMENT_PROGRAMME_PNER_ID ON convention_financement (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_CONVENTION_FINANCEMENT_PROJET_ELECTRIFICATION_ID ON convention_financement (projet_electrification_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONVENTION_FINANCEMENT_CODE ON convention_financement (code)');
        $this->addSql('ALTER TABLE convention_financement ADD CONSTRAINT FK_CONVENTION_FINANCEMENT_BAILLEUR_FONDS FOREIGN KEY (bailleur_fonds_id) REFERENCES bailleur_fonds (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE convention_financement ADD CONSTRAINT FK_CONVENTION_FINANCEMENT_SOURCE_FINANCEMENT FOREIGN KEY (source_financement_id) REFERENCES source_financement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE convention_financement ADD CONSTRAINT FK_CONVENTION_FINANCEMENT_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE convention_financement ADD CONSTRAINT FK_CONVENTION_FINANCEMENT_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE decaissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, convention_financement_id INT NOT NULL, projet_electrification_id INT DEFAULT NULL, montant_usd DOUBLE PRECISION NOT NULL, date_decaissement DATE NOT NULL, reference_paiement VARCHAR(100) DEFAULT NULL, objet TEXT DEFAULT NULL, statut VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DECAISSEMENT_CONVENTION_FINANCEMENT_ID ON decaissement (convention_financement_id)');
        $this->addSql('CREATE INDEX IDX_DECAISSEMENT_PROJET_ELECTRIFICATION_ID ON decaissement (projet_electrification_id)');
        $this->addSql('ALTER TABLE decaissement ADD CONSTRAINT FK_DECAISSEMENT_CONVENTION_FINANCEMENT FOREIGN KEY (convention_financement_id) REFERENCES convention_financement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE decaissement ADD CONSTRAINT FK_DECAISSEMENT_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE cout_previsionnel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, programme_pner_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, categorie_cout VARCHAR(50) NOT NULL, montant_usd DOUBLE PRECISION NOT NULL, annee SMALLINT DEFAULT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COUT_PREVISIONNEL_PROGRAMME_PNER_ID ON cout_previsionnel (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_COUT_PREVISIONNEL_PROJET_ELECTRIFICATION_ID ON cout_previsionnel (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_COUT_PREVISIONNEL_ZER_ID ON cout_previsionnel (zer_id)');
        $this->addSql('ALTER TABLE cout_previsionnel ADD CONSTRAINT FK_COUT_PREVISIONNEL_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cout_previsionnel ADD CONSTRAINT FK_COUT_PREVISIONNEL_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cout_previsionnel ADD CONSTRAINT FK_COUT_PREVISIONNEL_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cout_previsionnel DROP CONSTRAINT FK_COUT_PREVISIONNEL_ZER');
        $this->addSql('ALTER TABLE cout_previsionnel DROP CONSTRAINT FK_COUT_PREVISIONNEL_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE cout_previsionnel DROP CONSTRAINT FK_COUT_PREVISIONNEL_PROGRAMME_PNER');
        $this->addSql('ALTER TABLE decaissement DROP CONSTRAINT FK_DECAISSEMENT_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE decaissement DROP CONSTRAINT FK_DECAISSEMENT_CONVENTION_FINANCEMENT');
        $this->addSql('ALTER TABLE convention_financement DROP CONSTRAINT FK_CONVENTION_FINANCEMENT_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE convention_financement DROP CONSTRAINT FK_CONVENTION_FINANCEMENT_PROGRAMME_PNER');
        $this->addSql('ALTER TABLE convention_financement DROP CONSTRAINT FK_CONVENTION_FINANCEMENT_SOURCE_FINANCEMENT');
        $this->addSql('ALTER TABLE convention_financement DROP CONSTRAINT FK_CONVENTION_FINANCEMENT_BAILLEUR_FONDS');
        $this->addSql('ALTER TABLE source_financement DROP CONSTRAINT FK_SOURCE_FINANCEMENT_BAILLEUR_FONDS');
        $this->addSql('DROP TABLE cout_previsionnel');
        $this->addSql('DROP TABLE decaissement');
        $this->addSql('DROP TABLE convention_financement');
        $this->addSql('DROP TABLE source_financement');
        $this->addSql('DROP TABLE bailleur_fonds');
    }
}
