<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260605010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER core business referential tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE programme_pner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(30) NOT NULL, periode_debut SMALLINT NOT NULL, periode_fin SMALLINT NOT NULL, nombre_localites_prevues INT DEFAULT NULL, taux_electrification_cible DOUBLE PRECISION DEFAULT NULL, montant_previsionnel_usd DOUBLE PRECISION DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROGRAMME_PNER_CODE ON programme_pner (code)');

        $this->addSql('CREATE TABLE systeme_electrification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, tension_kv DOUBLE PRECISION DEFAULT NULL, rayon_km DOUBLE PRECISION DEFAULT NULL, source_energie VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SYSTEME_ELECTRIFICATION_CODE ON systeme_electrification (code)');

        $this->addSql('CREATE TABLE zer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(30) NOT NULL, superficie_km2 DOUBLE PRECISION DEFAULT NULL, population INT DEFAULT NULL, nombre_menages INT DEFAULT NULL, nombre_localites INT DEFAULT NULL, taux_localites_moins800_habitants DOUBLE PRECISION DEFAULT NULL, potentiel_solaire VARCHAR(100) DEFAULT NULL, potentiel_hydro VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ZER_CODE ON zer (code)');

        $this->addSql('CREATE TABLE prefecture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, zer_id INT NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PREFECTURE_ZER_ID ON prefecture (zer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PREFECTURE_CODE ON prefecture (code)');
        $this->addSql('ALTER TABLE prefecture ADD CONSTRAINT FK_PREFECTURE_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE sous_prefecture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prefecture_id INT NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SOUS_PREFECTURE_PREFECTURE_ID ON sous_prefecture (prefecture_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SOUS_PREFECTURE_CODE ON sous_prefecture (code)');
        $this->addSql('ALTER TABLE sous_prefecture ADD CONSTRAINT FK_SOUS_PREFECTURE_PREFECTURE FOREIGN KEY (prefecture_id) REFERENCES prefecture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE localite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prefecture_id INT DEFAULT NULL, sous_prefecture_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, programme_pner_id INT DEFAULT NULL, systeme_electrification_id INT DEFAULT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, nombre_menages INT DEFAULT NULL, population_totale INT DEFAULT NULL, categorie_population VARCHAR(80) DEFAULT NULL, statut_electrification VARCHAR(80) DEFAULT NULL, distance_reseau_km DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_LOCALITE_PREFECTURE_ID ON localite (prefecture_id)');
        $this->addSql('CREATE INDEX IDX_LOCALITE_SOUS_PREFECTURE_ID ON localite (sous_prefecture_id)');
        $this->addSql('CREATE INDEX IDX_LOCALITE_ZER_ID ON localite (zer_id)');
        $this->addSql('CREATE INDEX IDX_LOCALITE_PROGRAMME_PNER_ID ON localite (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_LOCALITE_SYSTEME_ELECTRIFICATION_ID ON localite (systeme_electrification_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LOCALITE_CODE ON localite (code)');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_LOCALITE_PREFECTURE FOREIGN KEY (prefecture_id) REFERENCES prefecture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_LOCALITE_SOUS_PREFECTURE FOREIGN KEY (sous_prefecture_id) REFERENCES sous_prefecture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_LOCALITE_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_LOCALITE_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_LOCALITE_SYSTEME_ELECTRIFICATION FOREIGN KEY (systeme_electrification_id) REFERENCES systeme_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE localite DROP CONSTRAINT FK_LOCALITE_SYSTEME_ELECTRIFICATION');
        $this->addSql('ALTER TABLE localite DROP CONSTRAINT FK_LOCALITE_PROGRAMME_PNER');
        $this->addSql('ALTER TABLE localite DROP CONSTRAINT FK_LOCALITE_ZER');
        $this->addSql('ALTER TABLE localite DROP CONSTRAINT FK_LOCALITE_SOUS_PREFECTURE');
        $this->addSql('ALTER TABLE localite DROP CONSTRAINT FK_LOCALITE_PREFECTURE');
        $this->addSql('ALTER TABLE sous_prefecture DROP CONSTRAINT FK_SOUS_PREFECTURE_PREFECTURE');
        $this->addSql('ALTER TABLE prefecture DROP CONSTRAINT FK_PREFECTURE_ZER');
        $this->addSql('DROP TABLE localite');
        $this->addSql('DROP TABLE sous_prefecture');
        $this->addSql('DROP TABLE prefecture');
        $this->addSql('DROP TABLE zer');
        $this->addSql('DROP TABLE systeme_electrification');
        $this->addSql('DROP TABLE programme_pner');
    }
}
