<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260606010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER GIS and cartography module tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE point_gps (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, altitude DOUBLE PRECISION DEFAULT NULL, precision_gps DOUBLE PRECISION DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');

        $this->addSql('CREATE TABLE infrastructure_electrique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, point_gps_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, nom VARCHAR(150) NOT NULL, type_infrastructure VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_INFRASTRUCTURE_ELECTRIQUE_POINT_GPS_ID ON infrastructure_electrique (point_gps_id)');
        $this->addSql('CREATE INDEX IDX_INFRASTRUCTURE_ELECTRIQUE_LOCALITE_ID ON infrastructure_electrique (localite_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INFRASTRUCTURE_ELECTRIQUE_CODE ON infrastructure_electrique (code)');
        $this->addSql('ALTER TABLE infrastructure_electrique ADD CONSTRAINT FK_INFRASTRUCTURE_ELECTRIQUE_POINT_GPS FOREIGN KEY (point_gps_id) REFERENCES point_gps (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE infrastructure_electrique ADD CONSTRAINT FK_INFRASTRUCTURE_ELECTRIQUE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE site_energetique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, localite_id INT NOT NULL, point_gps_id INT NOT NULL, code VARCHAR(50) NOT NULL, nom VARCHAR(150) NOT NULL, type_site VARCHAR(50) NOT NULL, puissance_installee_kw DOUBLE PRECISION DEFAULT NULL, statut VARCHAR(50) NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SITE_ENERGETIQUE_LOCALITE_ID ON site_energetique (localite_id)');
        $this->addSql('CREATE INDEX IDX_SITE_ENERGETIQUE_POINT_GPS_ID ON site_energetique (point_gps_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SITE_ENERGETIQUE_CODE ON site_energetique (code)');
        $this->addSql('ALTER TABLE site_energetique ADD CONSTRAINT FK_SITE_ENERGETIQUE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_energetique ADD CONSTRAINT FK_SITE_ENERGETIQUE_POINT_GPS FOREIGN KEY (point_gps_id) REFERENCES point_gps (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE donnee_geospatiale_localite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, localite_id INT NOT NULL, superficie_km2 DOUBLE PRECISION DEFAULT NULL, population_reference INT DEFAULT NULL, menages_reference INT DEFAULT NULL, densite_population DOUBLE PRECISION DEFAULT NULL, observations TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DONNEE_GEOSPATIALE_LOCALITE_LOCALITE_ID ON donnee_geospatiale_localite (localite_id)');
        $this->addSql('ALTER TABLE donnee_geospatiale_localite ADD CONSTRAINT FK_DONNEE_GEOSPATIALE_LOCALITE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE donnee_geospatiale_localite DROP CONSTRAINT FK_DONNEE_GEOSPATIALE_LOCALITE_LOCALITE');
        $this->addSql('ALTER TABLE site_energetique DROP CONSTRAINT FK_SITE_ENERGETIQUE_POINT_GPS');
        $this->addSql('ALTER TABLE site_energetique DROP CONSTRAINT FK_SITE_ENERGETIQUE_LOCALITE');
        $this->addSql('ALTER TABLE infrastructure_electrique DROP CONSTRAINT FK_INFRASTRUCTURE_ELECTRIQUE_LOCALITE');
        $this->addSql('ALTER TABLE infrastructure_electrique DROP CONSTRAINT FK_INFRASTRUCTURE_ELECTRIQUE_POINT_GPS');
        $this->addSql('DROP TABLE donnee_geospatiale_localite');
        $this->addSql('DROP TABLE site_energetique');
        $this->addSql('DROP TABLE infrastructure_electrique');
        $this->addSql('DROP TABLE point_gps');
    }
}
