<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260608000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER gender and inclusion module tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE action_genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, programme_pner_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, titre VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, axe_strategique VARCHAR(50) NOT NULL, statut VARCHAR(30) NOT NULL, date_debut_prevue DATE DEFAULT NULL, date_fin_prevue DATE DEFAULT NULL, date_debut_effective DATE DEFAULT NULL, date_fin_effective DATE DEFAULT NULL, responsable VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACTION_GENRE_CODE ON action_genre (code)');
        $this->addSql('CREATE INDEX IDX_ACTION_GENRE_PROGRAMME_PNER_ID ON action_genre (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_ACTION_GENRE_PROJET_ELECTRIFICATION_ID ON action_genre (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_ACTION_GENRE_ZER_ID ON action_genre (zer_id)');
        $this->addSql('CREATE INDEX IDX_ACTION_GENRE_LOCALITE_ID ON action_genre (localite_id)');
        $this->addSql('ALTER TABLE action_genre ADD CONSTRAINT FK_ACTION_GENRE_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_genre ADD CONSTRAINT FK_ACTION_GENRE_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_genre ADD CONSTRAINT FK_ACTION_GENRE_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action_genre ADD CONSTRAINT FK_ACTION_GENRE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE beneficiaire_genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_genre_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, categorie_beneficiaire VARCHAR(50) NOT NULL, nombre_hommes INT NOT NULL, nombre_femmes INT NOT NULL, nombre_jeunes INT NOT NULL, nombre_personnes_vulnerables INT NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BENEFICIAIRE_GENRE_ACTION_GENRE_ID ON beneficiaire_genre (action_genre_id)');
        $this->addSql('CREATE INDEX IDX_BENEFICIAIRE_GENRE_PROJET_ELECTRIFICATION_ID ON beneficiaire_genre (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_BENEFICIAIRE_GENRE_LOCALITE_ID ON beneficiaire_genre (localite_id)');
        $this->addSql('ALTER TABLE beneficiaire_genre ADD CONSTRAINT FK_BENEFICIAIRE_GENRE_ACTION_GENRE FOREIGN KEY (action_genre_id) REFERENCES action_genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE beneficiaire_genre ADD CONSTRAINT FK_BENEFICIAIRE_GENRE_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE beneficiaire_genre ADD CONSTRAINT FK_BENEFICIAIRE_GENRE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE formation_genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_genre_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, intitule VARCHAR(200) NOT NULL, date_formation DATE DEFAULT NULL, nombre_participants INT NOT NULL, nombre_femmes INT NOT NULL, nombre_hommes INT NOT NULL, theme VARCHAR(200) NOT NULL, formateur VARCHAR(150) DEFAULT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FORMATION_GENRE_CODE ON formation_genre (code)');
        $this->addSql('CREATE INDEX IDX_FORMATION_GENRE_ACTION_GENRE_ID ON formation_genre (action_genre_id)');
        $this->addSql('CREATE INDEX IDX_FORMATION_GENRE_ZER_ID ON formation_genre (zer_id)');
        $this->addSql('CREATE INDEX IDX_FORMATION_GENRE_LOCALITE_ID ON formation_genre (localite_id)');
        $this->addSql('ALTER TABLE formation_genre ADD CONSTRAINT FK_FORMATION_GENRE_ACTION_GENRE FOREIGN KEY (action_genre_id) REFERENCES action_genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_genre ADD CONSTRAINT FK_FORMATION_GENRE_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_genre ADD CONSTRAINT FK_FORMATION_GENRE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE indicateur_genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_genre_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, valeur_reference DOUBLE PRECISION DEFAULT NULL, valeur_cible DOUBLE PRECISION DEFAULT NULL, valeur_actuelle DOUBLE PRECISION DEFAULT NULL, unite VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INDICATEUR_GENRE_CODE ON indicateur_genre (code)');
        $this->addSql('CREATE INDEX IDX_INDICATEUR_GENRE_ACTION_GENRE_ID ON indicateur_genre (action_genre_id)');
        $this->addSql('CREATE INDEX IDX_INDICATEUR_GENRE_PROJET_ELECTRIFICATION_ID ON indicateur_genre (projet_electrification_id)');
        $this->addSql('ALTER TABLE indicateur_genre ADD CONSTRAINT FK_INDICATEUR_GENRE_ACTION_GENRE FOREIGN KEY (action_genre_id) REFERENCES action_genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE indicateur_genre ADD CONSTRAINT FK_INDICATEUR_GENRE_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE comite_genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, zer_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, nom VARCHAR(200) NOT NULL, type_comite VARCHAR(40) NOT NULL, date_mise_en_place DATE DEFAULT NULL, nombre_membres INT NOT NULL, nombre_femmes INT NOT NULL, nombre_hommes INT NOT NULL, statut VARCHAR(30) NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMITE_GENRE_CODE ON comite_genre (code)');
        $this->addSql('CREATE INDEX IDX_COMITE_GENRE_ZER_ID ON comite_genre (zer_id)');
        $this->addSql('CREATE INDEX IDX_COMITE_GENRE_LOCALITE_ID ON comite_genre (localite_id)');
        $this->addSql('ALTER TABLE comite_genre ADD CONSTRAINT FK_COMITE_GENRE_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comite_genre ADD CONSTRAINT FK_COMITE_GENRE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE comite_genre DROP CONSTRAINT FK_COMITE_GENRE_LOCALITE');
        $this->addSql('ALTER TABLE comite_genre DROP CONSTRAINT FK_COMITE_GENRE_ZER');
        $this->addSql('ALTER TABLE indicateur_genre DROP CONSTRAINT FK_INDICATEUR_GENRE_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE indicateur_genre DROP CONSTRAINT FK_INDICATEUR_GENRE_ACTION_GENRE');
        $this->addSql('ALTER TABLE formation_genre DROP CONSTRAINT FK_FORMATION_GENRE_LOCALITE');
        $this->addSql('ALTER TABLE formation_genre DROP CONSTRAINT FK_FORMATION_GENRE_ZER');
        $this->addSql('ALTER TABLE formation_genre DROP CONSTRAINT FK_FORMATION_GENRE_ACTION_GENRE');
        $this->addSql('ALTER TABLE beneficiaire_genre DROP CONSTRAINT FK_BENEFICIAIRE_GENRE_LOCALITE');
        $this->addSql('ALTER TABLE beneficiaire_genre DROP CONSTRAINT FK_BENEFICIAIRE_GENRE_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE beneficiaire_genre DROP CONSTRAINT FK_BENEFICIAIRE_GENRE_ACTION_GENRE');
        $this->addSql('ALTER TABLE action_genre DROP CONSTRAINT FK_ACTION_GENRE_LOCALITE');
        $this->addSql('ALTER TABLE action_genre DROP CONSTRAINT FK_ACTION_GENRE_ZER');
        $this->addSql('ALTER TABLE action_genre DROP CONSTRAINT FK_ACTION_GENRE_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE action_genre DROP CONSTRAINT FK_ACTION_GENRE_PROGRAMME_PNER');
        $this->addSql('DROP TABLE comite_genre');
        $this->addSql('DROP TABLE indicateur_genre');
        $this->addSql('DROP TABLE formation_genre');
        $this->addSql('DROP TABLE beneficiaire_genre');
        $this->addSql('DROP TABLE action_genre');
    }
}
