<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260606000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER rural electrification project module tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE projet_electrification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, programme_pner_id INT NOT NULL, zer_id INT DEFAULT NULL, systeme_electrification_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, intitule VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(30) NOT NULL, date_debut_prevue DATE NOT NULL, date_fin_prevue DATE NOT NULL, date_debut_effective DATE DEFAULT NULL, date_fin_effective DATE DEFAULT NULL, montant_previsionnel_usd DOUBLE PRECISION DEFAULT NULL, montant_mobilise_usd DOUBLE PRECISION DEFAULT NULL, source_financement VARCHAR(150) DEFAULT NULL, maitre_ouvrage VARCHAR(150) DEFAULT NULL, partenaire_technique VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PROJET_ELECTRIFICATION_PROGRAMME_PNER_ID ON projet_electrification (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_PROJET_ELECTRIFICATION_ZER_ID ON projet_electrification (zer_id)');
        $this->addSql('CREATE INDEX IDX_PROJET_ELECTRIFICATION_SYSTEME_ELECTRIFICATION_ID ON projet_electrification (systeme_electrification_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROJET_ELECTRIFICATION_CODE ON projet_electrification (code)');
        $this->addSql('ALTER TABLE projet_electrification ADD CONSTRAINT FK_PROJET_ELECTRIFICATION_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_electrification ADD CONSTRAINT FK_PROJET_ELECTRIFICATION_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_electrification ADD CONSTRAINT FK_PROJET_ELECTRIFICATION_SYSTEME_ELECTRIFICATION FOREIGN KEY (systeme_electrification_id) REFERENCES systeme_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE projet_localite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, projet_electrification_id INT NOT NULL, localite_id INT NOT NULL, statut_localite VARCHAR(30) NOT NULL, date_raccordement_prevue DATE DEFAULT NULL, date_raccordement_effective DATE DEFAULT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PROJET_LOCALITE_PROJET_ELECTRIFICATION_ID ON projet_localite (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_PROJET_LOCALITE_LOCALITE_ID ON projet_localite (localite_id)');
        $this->addSql('ALTER TABLE projet_localite ADD CONSTRAINT FK_PROJET_LOCALITE_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_localite ADD CONSTRAINT FK_PROJET_LOCALITE_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE phase_projet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, projet_electrification_id INT NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, ordre INT NOT NULL, statut VARCHAR(30) NOT NULL, date_debut_prevue DATE DEFAULT NULL, date_fin_prevue DATE DEFAULT NULL, date_debut_effective DATE DEFAULT NULL, date_fin_effective DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_PHASE_PROJET_PROJET_ELECTRIFICATION_ID ON phase_projet (projet_electrification_id)');
        $this->addSql('ALTER TABLE phase_projet ADD CONSTRAINT FK_PHASE_PROJET_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE activite_projet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phase_projet_id INT NOT NULL, libelle VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(30) NOT NULL, taux_execution DOUBLE PRECISION NOT NULL, date_debut_prevue DATE DEFAULT NULL, date_fin_prevue DATE DEFAULT NULL, date_debut_effective DATE DEFAULT NULL, date_fin_effective DATE DEFAULT NULL, responsable VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ACTIVITE_PROJET_PHASE_PROJET_ID ON activite_projet (phase_projet_id)');
        $this->addSql('ALTER TABLE activite_projet ADD CONSTRAINT FK_ACTIVITE_PROJET_PHASE_PROJET FOREIGN KEY (phase_projet_id) REFERENCES phase_projet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE activite_projet DROP CONSTRAINT FK_ACTIVITE_PROJET_PHASE_PROJET');
        $this->addSql('ALTER TABLE phase_projet DROP CONSTRAINT FK_PHASE_PROJET_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE projet_localite DROP CONSTRAINT FK_PROJET_LOCALITE_LOCALITE');
        $this->addSql('ALTER TABLE projet_localite DROP CONSTRAINT FK_PROJET_LOCALITE_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE projet_electrification DROP CONSTRAINT FK_PROJET_ELECTRIFICATION_SYSTEME_ELECTRIFICATION');
        $this->addSql('ALTER TABLE projet_electrification DROP CONSTRAINT FK_PROJET_ELECTRIFICATION_ZER');
        $this->addSql('ALTER TABLE projet_electrification DROP CONSTRAINT FK_PROJET_ELECTRIFICATION_PROGRAMME_PNER');
        $this->addSql('DROP TABLE activite_projet');
        $this->addSql('DROP TABLE phase_projet');
        $this->addSql('DROP TABLE projet_localite');
        $this->addSql('DROP TABLE projet_electrification');
    }
}
