<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260606020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PNER monitoring and evaluation module tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE indicateur_pner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, type_indicateur VARCHAR(50) NOT NULL, unite VARCHAR(50) NOT NULL, valeur_reference DOUBLE PRECISION DEFAULT NULL, valeur_cible DOUBLE PRECISION DEFAULT NULL, frequence_suivi VARCHAR(30) NOT NULL, source_donnee VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INDICATEUR_PNER_CODE ON indicateur_pner (code)');

        $this->addSql('CREATE TABLE valeur_indicateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, indicateur_pner_id INT NOT NULL, programme_pner_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, periode VARCHAR(30) NOT NULL, annee SMALLINT NOT NULL, valeur DOUBLE PRECISION NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_VALEUR_INDICATEUR_INDICATEUR_PNER_ID ON valeur_indicateur (indicateur_pner_id)');
        $this->addSql('CREATE INDEX IDX_VALEUR_INDICATEUR_PROGRAMME_PNER_ID ON valeur_indicateur (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_VALEUR_INDICATEUR_ZER_ID ON valeur_indicateur (zer_id)');
        $this->addSql('CREATE INDEX IDX_VALEUR_INDICATEUR_PROJET_ELECTRIFICATION_ID ON valeur_indicateur (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_VALEUR_INDICATEUR_LOCALITE_ID ON valeur_indicateur (localite_id)');
        $this->addSql('ALTER TABLE valeur_indicateur ADD CONSTRAINT FK_VALEUR_INDICATEUR_INDICATEUR_PNER FOREIGN KEY (indicateur_pner_id) REFERENCES indicateur_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE valeur_indicateur ADD CONSTRAINT FK_VALEUR_INDICATEUR_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE valeur_indicateur ADD CONSTRAINT FK_VALEUR_INDICATEUR_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE valeur_indicateur ADD CONSTRAINT FK_VALEUR_INDICATEUR_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE valeur_indicateur ADD CONSTRAINT FK_VALEUR_INDICATEUR_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE rapport_suivi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, programme_pner_id INT DEFAULT NULL, zer_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, titre VARCHAR(200) NOT NULL, type_rapport VARCHAR(50) NOT NULL, periode_debut DATE NOT NULL, periode_fin DATE NOT NULL, resume TEXT DEFAULT NULL, recommandations TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RAPPORT_SUIVI_PROGRAMME_PNER_ID ON rapport_suivi (programme_pner_id)');
        $this->addSql('CREATE INDEX IDX_RAPPORT_SUIVI_ZER_ID ON rapport_suivi (zer_id)');
        $this->addSql('CREATE INDEX IDX_RAPPORT_SUIVI_PROJET_ELECTRIFICATION_ID ON rapport_suivi (projet_electrification_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RAPPORT_SUIVI_CODE ON rapport_suivi (code)');
        $this->addSql('ALTER TABLE rapport_suivi ADD CONSTRAINT FK_RAPPORT_SUIVI_PROGRAMME_PNER FOREIGN KEY (programme_pner_id) REFERENCES programme_pner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rapport_suivi ADD CONSTRAINT FK_RAPPORT_SUIVI_ZER FOREIGN KEY (zer_id) REFERENCES zer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rapport_suivi ADD CONSTRAINT FK_RAPPORT_SUIVI_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE observation_suivi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rapport_suivi_id INT DEFAULT NULL, projet_electrification_id INT DEFAULT NULL, localite_id INT DEFAULT NULL, titre VARCHAR(200) NOT NULL, description TEXT NOT NULL, niveau_criticite VARCHAR(30) NOT NULL, statut VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_OBSERVATION_SUIVI_RAPPORT_SUIVI_ID ON observation_suivi (rapport_suivi_id)');
        $this->addSql('CREATE INDEX IDX_OBSERVATION_SUIVI_PROJET_ELECTRIFICATION_ID ON observation_suivi (projet_electrification_id)');
        $this->addSql('CREATE INDEX IDX_OBSERVATION_SUIVI_LOCALITE_ID ON observation_suivi (localite_id)');
        $this->addSql('ALTER TABLE observation_suivi ADD CONSTRAINT FK_OBSERVATION_SUIVI_RAPPORT_SUIVI FOREIGN KEY (rapport_suivi_id) REFERENCES rapport_suivi (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE observation_suivi ADD CONSTRAINT FK_OBSERVATION_SUIVI_PROJET_ELECTRIFICATION FOREIGN KEY (projet_electrification_id) REFERENCES projet_electrification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE observation_suivi ADD CONSTRAINT FK_OBSERVATION_SUIVI_LOCALITE FOREIGN KEY (localite_id) REFERENCES localite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE observation_suivi DROP CONSTRAINT FK_OBSERVATION_SUIVI_LOCALITE');
        $this->addSql('ALTER TABLE observation_suivi DROP CONSTRAINT FK_OBSERVATION_SUIVI_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE observation_suivi DROP CONSTRAINT FK_OBSERVATION_SUIVI_RAPPORT_SUIVI');
        $this->addSql('ALTER TABLE rapport_suivi DROP CONSTRAINT FK_RAPPORT_SUIVI_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE rapport_suivi DROP CONSTRAINT FK_RAPPORT_SUIVI_ZER');
        $this->addSql('ALTER TABLE rapport_suivi DROP CONSTRAINT FK_RAPPORT_SUIVI_PROGRAMME_PNER');
        $this->addSql('ALTER TABLE valeur_indicateur DROP CONSTRAINT FK_VALEUR_INDICATEUR_LOCALITE');
        $this->addSql('ALTER TABLE valeur_indicateur DROP CONSTRAINT FK_VALEUR_INDICATEUR_PROJET_ELECTRIFICATION');
        $this->addSql('ALTER TABLE valeur_indicateur DROP CONSTRAINT FK_VALEUR_INDICATEUR_ZER');
        $this->addSql('ALTER TABLE valeur_indicateur DROP CONSTRAINT FK_VALEUR_INDICATEUR_PROGRAMME_PNER');
        $this->addSql('ALTER TABLE valeur_indicateur DROP CONSTRAINT FK_VALEUR_INDICATEUR_INDICATEUR_PNER');
        $this->addSql('DROP TABLE observation_suivi');
        $this->addSql('DROP TABLE rapport_suivi');
        $this->addSql('DROP TABLE valeur_indicateur');
        $this->addSql('DROP TABLE indicateur_pner');
    }
}
